
const EFFECT_TYPES = {
  PUT: 'PUT',
  CALL: 'CALL',
  TAKE: 'TAKE',
  TAKE_ALL: 'TAKE_ALL',
  TAKE_ONE: 'TAKE_ONE',
  TAKE_LATEST: 'TAKE_LATEST',
  TAKE_AND_DELAY: 'TAKE_AND_DELAY',
}

exports.EFFECT_TYPES = EFFECT_TYPES